name: OL_mrcnn
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.9.18
  - pip:
      - h5py==3.10.0
      - imageio==2.33.1
      - imagecodecs=2024.1.1
      - imgaug==0.4.0
      - keras==2.15.0
      - matplotlib==3.8.2
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - pandas==2.2.0
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - sphinx==7.2.6
      - tensorboard==2.15.1
      - tensorflow==2.15.0
      - tifffile==2024.1.30
      - tqdm==4.66.2