name: tf_test
channels:
  - defaults
  - conda-forge
  #bioformats_jar
dependencies:
  - python=3.9.19
  - pip:
      - numpy==1.26.4
      - scikit-image==0.22.0
      - opencv-python==4.9.0.80
      - matplotlib==3.9.0
      - ipython==8.18.1
      - tensorflow==2.15.0
      - pandas==2.2.2
      - seaborn==0.13.2
      - scikit-learn==1.5.0
      - imgaug==0.4.0
      - argparse==1.4.0
      - aicsimageio==4.14.0
      #- python-bioformats==4.0.7